### ISSUE TITLE
You should use the new connection category API.

### ISSUE THREAD

**Issue by LuziferSenpai** [protocol-1903/no-pipe-touching#18]
Hey,

there is a new api called [Connection category](https://lua-api.factorio.com/2.0.10/types/PipeConnectionDefinition.html#connection_category), which allows you to set categories which then only will allow the fluid_boxes with these categories to connect.

**Comment by protocol-1903** [comment]
This would work, but is not dynamically applicable to pipes in-game, so you would need separate pipe entities per fluid. Other mods do this already iirc, i have a different idea in mind using scripting

**Comment by LuziferSenpai** [comment]
Not really? https://mods.factorio.com/mod/RGBPipes

**Comment by protocol-1903** [comment]
Ah, i had the application backwards. Thanks, I'll look into applying it retroactively (and hopefully not breaking everything in the process)
